# This is a basic workflow to help you get started with Actions

name: Update Documentation

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]


  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  - name: Doxygen Action
    uses: mattnotmitt/doxygen-action@1.9.1